# CONFIGURAÇÃO DO BANCO EM ARQUIVO (DADOS NÃO SOMEM MAIS)
spring.datasource.url=jdbc:h2:file:./data/mygymdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o console web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mantém a estrutura das tabelas atualizada sem deletar os dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect